apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: applications
  namespace: argocd
spec:
  project: default

  destination:
    server: https://kubernetes.default.svc
    namespace: argocd

  sources:
    - repoURL: https://github.com/ViniciusPilan/homelab.git
      targetRevision: main
      path: systems/k8s-cluster/tools/argo/applications

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
