apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
spec:
  project: default

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring

  sources:
    - repoURL: https://grafana-community.github.io/helm-charts
      chart: grafana
      targetRevision: 13.2.6
      helm:
        releaseName: grafana
        valueFiles:
          - $values/systems/k8s-cluster/tools/grafana/values.yaml

    - repoURL: https://github.com/ViniciusPilan/homelab.git
      targetRevision: main
      ref: values

  syncPolicy:
    # automated:
    #   prune: true
    #   selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
