apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-ingress
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default

  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system

  sources:
    # Istio gateway
    - repoURL: https://istio-release.storage.googleapis.com/charts
      chart: gateway
      targetRevision: 1.30.1
      helm:
        releaseName: istio-ingress
        valueFiles:
          - $values/systems/k8s-cluster/tools/istio/gateway/values.yaml

    - repoURL: https://github.com/ViniciusPilan/homelab.git
      targetRevision: main
      ref: values

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
