apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kyverno
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default

  destination:
    server: https://kubernetes.default.svc
    namespace: kyverno

  sources:
    - repoURL: https://kyverno.github.io/kyverno
      chart: kyverno
      targetRevision: 3.9.1
      helm:
        releaseName: kyverno
        valueFiles:
          - $values/systems/k8s-cluster/tools/kyverno/values.yaml

    - repoURL: https://github.com/ViniciusPilan/homelab.git
      targetRevision: main
      ref: values

    - repoURL: https://github.com/ViniciusPilan/homelab.git
      targetRevision: main
      path: systems/k8s-cluster/tools/kyverno/policies


  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
